.TH RSCALC 1
.SH NAME
rscalc \- A cli based calculator in rust.
.SH SYNOPSIS
\fBrscalc\fR path
.SH FEATURES
Operators
    \- `+` for Addition
    \- `\-` for Subtraction
    \- `*` for Multiplication
    \- `/` for Division
    \- `^` for Power


.SH EXIT STATUS
.TP
\fB0\fR
Successful program execution.

.TP
\fB1\fR
Unsuccessful program execution.

.TP
\fB101\fR
The program panicked.
.SH EXAMPLES
.TP
Running the program
\fB$ rscalc\fR

.SH AUTHOR
.P
.RS 2
.nf
Takashi I <mail@takashiidobe.com>
